### ISSUE TITLE
Background looks weird sometimes

### ISSUE THREAD

**Issue by raulvillares** [raulvillares/3sacrowd#13]
If the board is big enough, the background starts again.

![image](https://user-images.githubusercontent.com/19681704/26901000-74cf65a2-4bd4-11e7-8b29-fd5eba989549.png)

Similar thing happens when using a mobile.

Related to #3

**Comment by thecoderunner** [comment]
Hi,
I have made a pull request to fix this. Please see pull request #14

**Comment by raulvillares** [comment]
Bang on. Thanks for your help @thecoderunner !

**Comment by thecoderunner** [comment]
I created of gif to demonstrate the issue and the fix.
![bgfix](https://user-images.githubusercontent.com/10985682/26999682-06cc62d8-4de3-11e7-974e-e567a66703fd.gif)

**Comment by raulvillares** [comment]
Nice.
