### ISSUE TITLE
Better frame for pinned squares

### ISSUE THREAD

**Issue by raulvillares** [raulvillares/3sacrowd#2]
When the player selects the pin tool and pins a square the game shows a frame around the pinned square. It could really be visually nicer.

![image](https://cloud.githubusercontent.com/assets/19681704/26787637/06a90968-4a0b-11e7-9d17-6c2b03055cb6.png)

**Comment by infinityl00p** [comment]
Hi @raulvillares, I played around with different designs, and without disrupting the flow of the page and the spacing between squares, this is what I came up with. Let me know what ya think or if you have any suggestions and I will update and create a PR. Cheers.


![pin](https://user-images.githubusercontent.com/16076300/26995304-b073d9b0-4d20-11e7-872b-3124d5c984e8.jpg)

**Comment by raulvillares** [comment]
I like that one much more than the current one. Feel free to create a PR.

![image](https://user-images.githubusercontent.com/19681704/26995506-58a4ea56-4d6d-11e7-9e19-f8b145b4f2db.png)

Thank you!

**Comment by raulvillares** [comment]
Ei @infinityl00p . I have make a little change so the css change of style is not hardcoded in the javascript file:

[See file changes](https://github.com/raulvillares/3sacrowd/commit/cff1a5cba29a917514377f032bb3ab0aa9034814)
