### ISSUE TITLE
Add favicon and title

### ISSUE THREAD

**Issue by raulvillares** [raulvillares/3sacrowd#21]
Title: 3sacrowd!
Favicon: https://github.com/raulvillares/3sacrowd/blob/master/img/squares/pink.png

**Comment by antnh6** [comment]
Can I give it a shot?

**Comment by raulvillares** [comment]
Go for it @antnh6 !

Thanks.

**Comment by LiamMorgan** [comment]
I'll have it if @antnh6 doesn't.

**Comment by raulvillares** [comment]
Thanks for your interest @LiamMorgan . Issue is now closed. Maybe you could work on some other  issue or think in a new feature.

Thanks again!
