### ISSUE TITLE
Medals for achievements

### ISSUE THREAD

**Issue by raulvillares** [raulvillares/3sacrowd#24]
Implement the possibility to win 3 medals for every level, each one for some kind of achievement:

1. Medal 1: Complete the level in less tan X time
2. Medal 2: Complete the level with less than X movements
3. Medal 3: Complete the level in a row (without undo a movement (neither with the undo button nor changing a square manually back to empty).

Achievements 1 and 2 must by configured in the [levels.js](https://github.com/raulvillares/3sacrowd/blob/master/js/levels.js) file.

When the level is completed, show the number of achievements with the [help of this images](https://github.com/raulvillares/3sacrowd/tree/master/img/medals) (medal_on is the achievement is completed, medal_off if not).

![image](https://user-images.githubusercontent.com/19681704/27274650-812bb1bc-54d4-11e7-9a3d-c6edeb6fb2a0.png)
![image](https://user-images.githubusercontent.com/19681704/27274662-8a370ffe-54d4-11e7-9fae-64844eb41bd1.png)

This can be done **incrementally** (for example: one PR for changing the level.js file to configure achievements for every level, another PR to show the number of movements regarding the max movements (8/25),... and so on.

**Comment by raulvillares** [comment]
A prototype is worth a thousand meetings:

![image](https://user-images.githubusercontent.com/19681704/27682807-2a79bb14-5cc4-11e7-9995-239d06d8793f.png)

**Comment by dallmanr** [comment]
I am interested in trying this. Having never worked on anything open source before this seems like a fun project to start. Do you have a time in mind for the levels? I am not sure if it is specified anywhere.

**Comment by raulvillares** [comment]
Hi @dallmanr ! Thanks for your interest.

@michaelkoska is working on this but we think there is room for you. Maybe you both can distribute the work. I see four subissues:

1. The logic to evaluate achievement 1 (time)
2. The logic to evaluate achievement 2 (movements)
3. The logic to evaluate achievement 3 (no undo)
4. Rendering achievements when level is completed

Anyway, I'm open to suggestions. The goal of this project is to learn and have fun.

Michael is working on point 1. **How do you feel about it?**

Regarding max time for levels... I don't know, we have too choose a time that fits well with every level (no easy to achieve but not impossible).  Since it is configured in levels.js file, will be easy to change it if we feel there is a need to. Same thing to max number of movements.

Thanks!

**Comment by MhdTlb** [comment]
I want to participate in this project. 
Which task can I work on?

**Comment by raulvillares** [comment]
Hey @MhdTlb sorry for the delay, I've been busy these days. Thanks for your interest! What do you think about working on point 4 **Rendering achievements when level is completed**

You can mock 3 functions in level.js file (maxTimeAchieved, maxMovementsAchieved, noUndosAchieved) that return a fixed boolean value and use them to render the results when each level is completed.

Some other people can work on the real implementation of the 3 functions.

**Comment by SharayuM** [comment]
Hello. It seems a pretty interesting project. Is there anything I could help? I haven't done any open source contribution and looking forward to do this.

**Comment by raulvillares** [comment]
Hello @SharayuM , thanks for your interest! Sure you can help. This is a simple project to help people take their first steps in GitHub, so everybody is welcome.

Do yo want to work on this issue? I just merged a pull request by @michaelkoska that implements part of the features requested for this issue. We are going to complete it and improve it. If you're interested I can give you some directions.

Also, if you have any idea to improve the game... go for it. And I mean any idea, even rename a function or a variable.

**Comment by SharayuM** [comment]
Hello,
Thanks for your response. I do want to work on this project. Just wanted to
ask as from where should I start learning the implemented project.

Thank you.

**Comment by raulvillares** [comment]
Hi again @SharayuM ,

I don't know exactly what you mean. You can [clone the repository](https://github.com/raulvillares/3sacrowd.git) and take a look at the code.

**Comment by raulvillares** [comment]
> Hi,
> I am a first-timer and I would love to work on this project.

Great @krupam ! What about show the information about how to reach the medals? Now, info div shows this:

_level number · current time · current number of moves_

like

_1/19 · 00:21 · 3 moves_

It should show something like:

_1/19 · 00:21 (max 01:00) · 3 moves (max 30)_

Do you feel like working on it? Let me know if you need more informations about this.

**Comment by prabodhmeshram** [comment]
Hi,
Is this issue still open. This seems interesting. If there is any issue or feature need to be developed, I would love to contribute.
Thanks!

**Comment by raulvillares** [comment]
Thanks for your willing to help @prabodhmeshram 

Yes, there's one more thing it would be nice to have in order to complete this new feature. See my previous message:

https://github.com/raulvillares/3sacrowd/issues/24#issuecomment-322903340

**Comment by prabodhmeshram** [comment]
Sure @raulvillares . Will work on it.

**Comment by prabodhmeshram** [comment]
Added the Changes @raulvillares

**Comment by raulvillares** [comment]
Merged! Thanks for your work @prabodhmeshram .
