### ISSUE TITLE
Sound Doesn't Play 

### ISSUE THREAD

**Issue by KatFrog** [raulvillares/3sacrowd#39]
Using desktop Chrome v. 64 on Fedora

I noticed that there are supposed to be sounds, but I don't hear anything.  Plus the speaker icon doesn't show on the tab.

I checked inspect element and there are no errors in the console.  I opened a sound file and it plays in another tab.

**Comment by titivermeesch** [comment]
I can't really reproduce this error anymore on the latest chrome build. Please reopen this issue if it happens again.
