### ISSUE TITLE
Adding a vagrant file

### ISSUE THREAD

**Issue by jdbohrman** [raulvillares/3sacrowd#44]
I just came across this repo and thought you all might enjoy a Vagrantfile. Having a single disposable, consistent environment that isolates dependencies can really lower development times and help make sure everyone is on the same page environment wise.

**Comment by titivermeesch** [comment]
Do we really need Vagrant for this? It would maybe be better to have a correctly configured package file that will handle all the dependencies correctly. I guess this would fix the issue you are trying to resolve with Vagrant.
