### ISSUE TITLE
Names for badges hidden by board on Completed screen

### ISSUE THREAD

**Issue by iankameron** [raulvillares/3sacrowd#49]
I have seen this many times after completing the board. Spacing is maybe an issue for the "Speed Demon" text as well, but the "No Looking Back!" goes under the board.

![image](https://user-images.githubusercontent.com/38037829/59889710-94496d00-9408-11e9-82c4-fab10d8762c9.png)

Seen in Chrome 74,75

**Comment by Apurva101** [comment]
Hi, this issue has been resolved. Here's link to my pull request
#https://github.com/raulvillares/3sacrowd/pull/52
![image](https://user-images.githubusercontent.com/46521835/83737999-5c672400-a671-11ea-8a12-2d4134d99f81.png)

**Comment by titivermeesch** [comment]
I'll have a look at this and merge it if it's ok.

**Comment by titivermeesch** [comment]
Issue resolved
