### ISSUE TITLE
Update readme file to show the instruction on how to run the project

### ISSUE THREAD

**Issue by keertirajmalik** [raulvillares/3sacrowd#62]
Hi, Can you please add some instructions about how to start the project for both deployments and development?

From what is seen in the readme file only testing instruction is there. Please update the readme file. It would help the newcomers who want to work on the project

**Comment by titivermeesch** [comment]
@keertirajmalik You should just open the main html file and it will load the app.
But indeed some more information is maybe better

**Comment by TKHV** [comment]
I've addded a few more instructions based on this, in pull req #64
