### ISSUE TITLE
Tests will not run, given the provided command in README.md file. 

### ISSUE THREAD

**Issue by OleDakotaJoe** [raulvillares/3sacrowd#66]
# Problem: when running the command "node -r ./test/entryFileTest.js" The command does not run and throws an erroe in the console: 
![image](https://user-images.githubusercontent.com/65524285/106428086-029c4100-642e-11eb-8483-fee5ba063e72.png)

Expected behavior: expects the tests to run.

**Comment by titivermeesch** [comment]
Covered in #67
