### ISSUE TITLE
Limit previous / next level buttons

### ISSUE THREAD

**Issue by raulvillares** [raulvillares/3sacrowd#7]
At first level, _previous level_ button makes no sense. Same for _next level_ button at last level.

**Comment by evanscloud** [comment]
Hey @raulvillares, first timer here. Can I work on this issue?

**Comment by raulvillares** [comment]
Sure @evanscloud ! That's the spirit. Let me know if you need something.

Thanks!

**Comment by raulvillares** [comment]
Thanks @evanscloud !
