### ISSUE TITLE
More levels

### ISSUE THREAD

**Issue by raulvillares** [raulvillares/3sacrowd#8]
Add more levels. See [levels.js](https://github.com/raulvillares/3sacrowd/blob/master/js/levels.js) file. Pretty straight forward.

Levels can be found [here](http://www2.stetson.edu/~efriedma/puzzle/tic/). You can design your own levels too!

**Comment by mrhill7** [comment]
Could I be assigned to work on this issue?

**Comment by raulvillares** [comment]
Sure! Let me know if you need any help.

**Comment by mrhill7** [comment]
Will do thanks for letting me collaborate.

**Comment by mrhill7** [comment]
I've submitted a pull request so you can review the changes.
